---
- hosts: localhost
  gather_facts: no
  tasks:

  - name: Create docker containers
    command: docker-compose -f ./docker-compose.yml up -d
    register: dockeroutput

  - name: Install dependencies on apache
    shell: docker exec -t apache bash -c 'apt-get update;apt-get install php5 php5-mysql vim git mysql-client -y ;a2enmod rewrite;/etc/init.d/apache2 stop;/etc/init.d/apache2 start'
    register: output
  - debug: var=output.stdout_lines

  - name: Copy apache config
    shell: docker cp ./httpd.conf apache:/usr/local/apache2/conf/httpd.conf
    register: output
  - debug: var=output.stdout_lines
